version: '1'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: my-jenkins1
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_vol:/var/jenkins_home


volumes:
  jenkins_vol: